---

# /etc/default/docker
# /lib/systemd/system/docker.service
# /etc/systemd/system/docker.service.d/docker.conf
# /etc/docker/daemon.json

# TODO
#nano /usr/lib/systemd/system/docker.service
# Add `Restart=always` under [Service]

# 4.5 environment
- name: Copy docker environment
  template:
    owner: root
    src: etc/environment.j2
    dest: /etc/environment

# 1.{5-13} Audit Rules
- name: Copy docker audit rules
  template:
    owner: root
    src: etc/audit/rules.d/docker.rules.j2
    dest: /etc/audit/rules.d/docker.rules

# TODO fix - not triggered
# service auditd restart
- name: Restart `auditd`
  systemd:
    name: auditd
    state: restarted
    daemon_reload: yes
  ignore_errors: yes



# 2.8 User namespace support
- name: Add User namespace support
  file:
    path: "{{ item }}"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"
  with_items:
    - /etc/subuid
    - /etc/subgid


# TODO TLS
# https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file
#{
#    "disable-legacy-registry": true,
#    "dns": [ "8.8.8.8", "8.8.4.4" ],
#    "icc": false,
#    "live-restore": true,
#    "log-level": "info",
#    "storage-driver": "overlay",
#
#	"tlsverify": true,
#	"tlscacert": "/root/.docker/ca.pem",
#	"tlscert": "/root/.docker/server-cert.pem",
#	"tlskey": "/root/.docker/server-key.pem",
#
#    "userland-proxy": false
#}

# Update docker deamon
# 2.1  "icc": true
# 2.2  "log-level":"info"
# 2.5  "storage-driver": "overlay" - https://docs.docker.com/engine/userguide/storagedriver/selectadriver/
# 2.8  "userns-remap": "??"
# 2.11 "authorization-plugins": [??]
# 2.12 "log-driver": "??", "log-opts": {??},
# 2.13 "disable-legacy-registry": true
# 2.14 "live-restore": true
# 2.18 "userland-proxy": false
- name: Update docker deamon
  template:
    owner: root
    src: etc/docker/daemon.json.j2
    dest: /etc/docker/daemon.json