---

# https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package

# 2017-03-21 etc/yum.repos.d/docker.repo from https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker yum repo
  template:
    owner: root
    src: etc/yum.repos.d/docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo

- name: Install docker
  yum:
    name: docker-ce
    state: present

- name: Start `docker`
  systemd:
    name: docker
    state: started
    enabled: yes

# Add users to docker
- name: Add users to docker group
  user:
    name:   "{{ item }}"
    group:  docker
  with_items:
    - "{{ docker_users }}"

- name: reload sshd
  notify:
    - reloaded sshd