---

- include: volumes.yml

- include: install.yml
  when: ansible_os_family == 'RedHat'

- include: auth-plugin.yml

- include: tls.yml

- include: config.yml

# TODO put when: configs change
- name: Restart `docker`
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes